### PR TITLE
Typescript rewrite

### LINKED ISSUE #14: Add typescript support
As titled :)

### PR DESCRIPTION
**Pull request by Teoxoy**
closes #14

### CODE REVIEW

**Comment by Teoxoy** [comment]
[`eslint`](https://github.com/eslint/eslint) with [`typescript-eslint`](https://github.com/typescript-eslint/typescript-eslint) could be setup to lint instead of `standard` but since the scope of the project is not that big I don't think it's worth it - typescript errors should suffice

**Comment by lependu** [comment]
Hi! Thanks for the PR and sorry for the late response. I was occupied. I look into it in the week.
 
I have one question though: is there a particular reason, why you choose to rewrite it in typescript instead of the [documented](https://www.fastify.io/docs/latest/TypeScript/) Fastify way of adding typescript support?

**Comment by Teoxoy** [comment]
I personally feel that I get a huge boost in productivity when working with typed javascript. I know some IDEs provide intellisense and linting even for javascript projects but that approach has limitations.

The plugin was simple enough to just be rewritten in typescript which was a plus.
Do you feel any particular way about typescript?

**Comment by lependu** [comment]
I have no feelings about typescript :) 

For me, the question is what this project gains with the switching to typescript. As you mentioned this is a very simple code base, which uses (or at least tries to use) the fact that javascript is not a strongly typed language.  

On the other hand, switching to typescript 
- introduces a compiling step 
- doesn't work with the Fastify standard linting method and linting would introduce further configuration steps.

So, in terms of maintainability switching comes with a negative balance for me, but please, correct me if I miss something.

**Comment by Teoxoy** [comment]
A pro would be not having to keep src and types in sync since they get generated.

**Comment by Teoxoy** [comment]
@lependu what's the status of this PR?

**Comment by lependu** [comment]
Hey @Teoxoy Since your last comment I moved forward and updated the repo to be compatible with `fastify@3.x` thats why the conflicts. 
Also, I don't use typescript and it would make much harder for me to maintain the repo if I would merge this PR.

**Pull request closed without merging**
